# Generated by Django 4.0.5 on 2022-06-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VHSER_MODULE', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vhser_vehicle',
            name='client_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
